spring:
  application:
    name: managesys
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://mysql/jx_queren?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    url: jdbc:mysql://192.168.1.26/scgltest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
#    url: jdbc:mysql://192.168.25.1/scgl?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    username: ss
    password: ss123456
  #    单个文件的大小
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 20234

mybatis-plus:
  mapper-locations: classpath*:/com/ss/managesys/mapper/**.xml
  type-aliases-package: com/ss/managesys/entity
  global-config:
    db-config:
      field-strategy: NOT_EMPTY

user:
  authOperator: 3
  authExaminer: 4
  proShishiZhong: 2